version: "3.8"
services:
  regularblog: 
    build: .
    container_name: blog_frontend
    stdin_open: true
    tty: true
    network_mode: "host"
    volumes:
      - ../blog-frontend:/app
      - ./app/node_modules